title: The Nifty Chips Laboratory @ HYU
logo: /assets/img/nifty_logo.png
description: The Nifty Chips Laboratory at Hanyang University is working on cool circuits and their automatic generators.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
